### ISSUE TITLE
Some (most?) of the examples are not showing up

### ISSUE THREAD

**Issue by borisvassilev** [SWI-Prolog/plweb-examples#3]
I tried to read README.md carefully but I am still not sure why only one of the maplist examples is showing up. The only example that shows up for me at the docs for maplist is the one from library/maplist_apply.md.

Similarly, length/2 is used in at least two of the examples, library/maplist_backtrack.md and library/maplist_fill.md, but only the first one is showing up in the docs for length/2.

**Comment by JanWielemaker** [comment]
Sorry.  Wrong sort/4 call that removed all examples with the same rank.   As each of them referenced the predicate with a single query, they all have the same rank, so one was left :cry:

**Comment by borisvassilev** [comment]
Great, thank you! I have collected a few examples, I will add them when I find time.
