### ISSUE TITLE
Should an example appear on all predicates used in the example?

### ISSUE THREAD

**Issue by dtonhofer** [SWI-Prolog/plweb-examples#6]
First, let me say that this is an excellent extension, although I had to look a bit around until I got that the examples are in a separate repository.

Now: I am not sure whether this is an issue or working as designed, but for example:

```
maplist_fill.md
```

... appears both for maplist/N and length/2 as example **Fill a list**. But for length/2 it is not an interesting example:

Not interesting:

![Screenshot_20210114_184333](https://user-images.githubusercontent.com/483879/104628542-a4830600-5698-11eb-83b4-c86f91547259.png)

Interesting:

![Screenshot_20210114_184657](https://user-images.githubusercontent.com/483879/104628797-f461cd00-5698-11eb-90a2-b45e0f81a37f.png)

Is this really right?

**Comment by JanWielemaker** [comment]
For now that is what happens.   The overall idea is that we rank the examples and will probably limit that to the top N at some point.  The ranking is now rather simple.  There are enough ways one can consider improving on that.

**Comment by dtonhofer** [comment]
All right. Let's accumulate those examples 👌
